### PR TITLE
refs #1 - PySkycoin . Initial code . Built using SWIG

### PR DESCRIPTION
**Pull request by stdevEclipse**
Skycoin Python library..

### CODE REVIEW

**Comment by stdevEclipse** [comment]
Hi. I created a new pull request for pyskycoin. Please, ignore this one. I had to create a new branch due to line-end incompatibility with Windows.
Sorry about that.

**Comment by olemis** [comment]
@stdevEclipse what's the right PR ? #2 or #3 ?

**Comment by stdevEclipse** [comment]
@olemis, sorry about the confusion with the PRs. I fixed the original. So, both are OK. We can keep this one, #2

**Comment by stdevEclipse** [comment]
Fixed by going one commit back and then pushing with -f. That should have done it

**Pull request merged**
